version: '3.7'

services:
  bot:
    command:
      - run-polling
    ports:
      - ${BOT_PUBLIC_PORT}:80

  redis:
    ports:
      - ${REDIS_PORT}:6379

  postgres:
    ports:
      - ${POSTGRES_PORT}:5432
